# Site settings
title: Podlets
email:
author: Podlets Authors
description:
url:
logo: podlets-logo.png
vm_logo: vm-logo.png
gh_repo: https://github.com/vmware/Kubelets/
hero: 
  background-color: dark-blue
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title: 
  cta_url: /docs/master
  cta_text: Documentation
  vm-link: http://vmware.github.io/
podcast: the-podlets
footer_social_links:
  Twitter:
    fa_icon: fab fa-twitter
    url: https://example.com
  Slack:
    fa_icon: fab fa-slack
    url: https://example.com
  RSS:
    fa_icon: fa fa-rss
    url: feed.xml

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "posts"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "episodes" 
    values:
      layout: "episodes"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  episodes:
    output: true
  contributors:

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)


# Include these subdirectories
include: 
  - CONTRIBUTING.md
  - README.md

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - LICENSE
  - CNAME
  - Runbook.docx
  - '*.sh'