toc:
  - title: Introduction
    subfolderitems:
      - page: About Tern
        url: /#what-is-tern
      - page: FAQ
        url: /faq
      - page: Glossary of Terms
        url: /glossary
      - page: Architecture
        url: /architecture
      - page: Navigating the Code
        url: /navigating-the-code
  - title: Getting Started
    subfolderitems:
      - page: Getting Started
        url: /#getting-started
      - page: Getting Started with Docker
        url: /#getting-started-with-docker
      - page: Getting Started with Vagrant
        url: /#getting-started-with-vagrant
      - page: Getting Started on Linux
        url: /#getting-started-on-linux
  - title: Using Tern
    subfolderitems:
      - page: Using Tern
        url: /#using-tern
      - page: Generating a BoM report for a Docker Image
        url: /#bom-for-docker-image
      - page: Generating a BoM report from a Dockerfile
        url: /#bom-for-dockerfile
  - title: Report Formats
    subfolderitems:
      - page: Report Formats
        url: /#report-formats
      - page: Human Readable Format
        url: /#report-human-readable
      - page: Summary Format
        url: /#report-summary
      - page: JSON Format
        url: /#report-json
      - page: YAML Format
        url: /#report-yaml
      - page: SPDX tag-value Format
        url: /#report-spdxtagvalue
  - title: Tern Project
    subfolderitems:
      - page: Running Tests
        url: /#running-tests
      - page: Project Status
        url: /#project-status
      - page: Documentation
        url: /#documentation
      - page: Contributing
        url: /#contributing